# ??????
server:
  port: 8000

# ??eureka??????
eureka:
  instance:
    hostname: localhost # ????
  client:
    registerWithEureka: false # ?????????????????????????
    fetchRegistry: false  # ???Eureka???????????????false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # Eureka??????

# ??????
spring:
  application:
    name: project-eureka